hardware_node:
  ros__parameters:
    serial_port: "/dev/ttyS1"
    left_enc_serial: 101902
    right_enc_serial: 102191
    wheel_radius: 0.05

    # PID Parameter
    #kp: 0.02004
    #ki: 0.40115
    #kd: 0.0

    kp_r: 1.0
    ki_r: 0.9
    kd_r: 0.0

    kp_l: 1.0
    ki_l: 0.9
    kd_l: 0.0

    # Physische Limits
    max_wheel_speed: 24.0  # rad/s
    deadband: 0.05
